### ISSUE TITLE
Passage Mismatch Lookup

### ISSUE THREAD

**Issue by johndoesniper** [seven1m/bible_api#56] opened 2021-07-26 05:59 UTC
Hi Tim,

I greatly appreciate the effort you've put in to this seamless API, but I wanted to bring it to your attention that as I looked up **Philippians 4**, I receive **Philippians 1:4** instead. I'm not sure if the reference is a one off as all other scriptures I've tried were correct so I believe the data to be mostly accurate. If you see the error is on my part and how I may address it, do let me know. I've noted the same for WEB and KJV translations. Provided is the link I submit [https://bible-api.com/Philippians 4](url), but should be expecting [https://bible-api.com/Philippians 4:1-23](url) as the results. Regards.

**Comment by seven1m** [comment] 2021-09-09 03:48
Sorry for the late reply. Thank you for reporting this.

Seems the issue is in this list of patterns: https://github.com/seven1m/bible_ref/blob/master/lib/bible_ref/languages/english.rb#L10

I believe it was supposed to match Philemon - not Philippians… 😬

**Comment by seven1m** [comment] 2021-11-30 04:07
Fixed in 0c2053717448986868d27879e5c3a8e069588f31.

**Closed by seven1m** 2021-11-30 04:07 UTC
Labels: bug
